// lib/aurora.ts
// Aurora DSQL connection pool using IAM token authenmtication.
//
// Aurora DSQL uses PostgreSQL wore protocol but authenticates via IAM
// tokens generated by DsqlSigner, not static passwords.
// Tokens expire after 15 minutes - the pool re-authenticates on error.

import { Pool, type QueryResultRow } from 'pg'
import { DsqlSigner } from '@aws-sdk/dsql-signer'
import { text } from 'stream/consumers'
import { get } from 'http'

let pool: Pool | null = null
let tokenExpiresAt = 0

async function generateToken(): Promise<string> {
    const signer = new DsqlSigner({
        hostname: process.env.AURORA_DSQL_ENDPOINT!,
        region: process.env.AWS_REGION ?? 'us-east-1',
        credentials: {
            accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
        },
    })
    // Tokens are valid for 15 minutes - regenerate 2 minutes before expiry
    tokenExpiresAt = Date.now() + 13 * 60 * 1000
    return signer.getDbConnectAdminAuthToken()
}

async function createpool(): Promise<Pool> {
    const token = await generateToken()

    const newPool = new Pool({
        host: process.env.AURORA_DSQL_ENDPOINT,
        port: 5432,
        database: 'postgres',
        user: 'admin',
        password: token,
        ssl: {
            // Aurora DSQL requires SSL - rejects invalid certs
            rejectUnauthorized: false,
        },
        max: 10,             // max pool connections
        min: 0,              // allow full scale-to-zero
        idleTimeoutMillis: 30_000,
        connectionTimeoutMillis: 5_000,
        // Auror DSQL is serverless - allow time for cold cluster wake
        query_timeout: 10_000,
    })

    newPool.on('error', (err) => {
        console.error('[aurora] Pool error - resetting:', err.message)
        pool = null
        tokenExpiresAt = 0
    })

    return newPool
}

export async function getPool(): Promise<Pool> {
    // Re-create pool if token is expired or pool was reset
    if (!pool || Date.now() > tokenExpiresAt) {
        if (pool) {
            // Gracefullt drain old pool before replacing
            await pool.end().catch(() => undefined)
        }
        pool = await createpool()
    }
    return pool
}


// ── Query helpers ───────────────────────────────────────────────────────────

export async function dbQuery<T extends QueryResultRow = QueryResultRow>(
    text: string,
    params: unknown[] = []
): Promise<T[]> {
    const db = await getPool()
    const result = await db.query<T>(text, params)
    return result.rows
}

export async function dbQueryOne<T extends QueryResultRow = QueryResultRow>(
    text: string,
    params: unknown[] = []
): Promise<T | null> {
    const rows = await dbQuery<T>(text, params)
    return rows[0] ?? null
}

export async function dbExecute(
    text: string,
    params: unknown[] = []
): Promise<number> {
    const db = await getPool()
    const result = await db.query(text, params)
    return result.rowCount ?? 0
}